@srv = http://localhost:8000

###
GET {{srv}}

###
GET {{srv}}/cursos

###
GET {{srv}}/cursos/19

###
POST {{srv}}/cursos
Content-Type: application/json

{
    "id": 12,
    "titulo": "Curso de manipulacao",
    "aulas": 2,
    "horas": 3.1

}