@srv = http://localhost:8000/v1

###
GET {{srv}}/cursos


###
POST {{srv}}/cursos
Content-Type: application/json

{
    "titulo": "CUrso de manunteção de notebooks",
    "horas": 45,
    "aulas": 32
}

###
GET {{srv}}/cursos/3

###
PUT {{srv}}/cursos/3
Content-Type: application/json

{
    "titulo": "CUrso de manunteção de manicure",
    "horas": 45,
    "aulas": 32
}

###
DELETE {{srv}}/cursos/3